:Author: gsrathore97
:Email:
:Date: 03/05/2024
:Revision: version#
:License: Public Domain

= Project: {Project}

AMIE Project 2024 Mechanical Engineering Govind Singh Rathore and FuturisticIOx, Gurgaon-122001 Wifi Internet(IoT) Controlled Hydraulic Scissor Lifter Model

Demo video link- https://youtube.com/shorts/fzsYE_GAf8o?si=kJaf6jXDZQ7R5idS
https://youtube.com/shorts/FdJ_jAWvT7A?si=79hkqa5x6cMPkRz5

Full explanation- https://youtu.be/STk515_Xuog?si=uG-z434zLvfvuuyh
https://youtu.be/LQLb9OUNvXU?si=7jGKMvCNRuBZbk1i

GitHub repository for code- https://github.com/gsrathore97/iot_Scissor_lifter_AMIE_Project_2024

Whole Project folder- https://drive.google.com/drive/folders/1Q-h4NLbMkmBsdpBlGQFpYtT1N3Pb2OyV


== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
