// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f821f8c0-60f1-4278-953a-aa4a881532db";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSpeedChange();
void onUpDownChange();

int speed;
int upDown;
bool lS1;
bool lS2;
bool deviceStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(speed, READWRITE, ON_CHANGE, onSpeedChange);
  ArduinoCloud.addProperty(upDown, READWRITE, ON_CHANGE, onUpDownChange);
  ArduinoCloud.addProperty(lS1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(lS2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deviceStatus, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
